---
title: "DS1_gtsummary"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## gtsummary 패키지 소개
gtsummary 패키지는 논문에 들어갈 **Table 1**을 만드는 데에 효율적으로 쓰일 수 있습니다.

-------------------------------------------------

## Setup

```{r, message = FALSE}
# install.packages("tidyverse")
# install.packages("data.table")
# install.packages("gtsummary")
# install.packages("smd")
library(tidyverse)
library(data.table)
library(gtsummary)
library(smd)
```

-------------------------------------------------

## Data load & Variable selection
연습을 위한 데이터셋을 만든다.

* 출처: <https://blog.zarathu.com/>

```{r, echo = FALSE}
url <- "https://raw.githubusercontent.com/jinseob2kim/lecture-snuhlab/master/data/example_g1e.csv"
dt <- fread(url, header=T)

# select variables
dt2 <- dt %>% select("EXMD_BZ_YYYY", "Q_PHX_DX_STK", "Q_SMK_YN",
                     "HGHT", "WGHT" ,"TOT_CHOL", "TG")
head(dt2)
```

-------------------------------------------------

## tbl_summary
tbl_summary는 다양한 옵션을 제공합니다.

* label : 테이블에 출력되는 변수명 지정  
* type : 변수 유형 지정 (ex. 연속형, 범주형)  
* statistic : 요약 통계량 지정  
* digits : 자릿수 지정  
* missing : 결측값이 있는 행을 표시할지 여부  
* missing_text : 결측행의 변수명 지정  
* sort : 빈도에 따라 범주형 변수의 level 정렬  
* percent : 열/행의 백분율 출력  
* include : 테이블에 포함할 변수 지정

```{r}
dt2 %>% select(-EXMD_BZ_YYYY) %>% tbl_summary()
dt2 %>%
  tbl_summary(
    by = EXMD_BZ_YYYY,
    statistic = list(all_continuous() ~ "{mean} ({sd})",
                     all_categorical() ~ "{n} / {N} ({p}%)"),
    label = Q_SMK_YN ~ "smoking y/n",
    missing_text = "Missing"
  ) %>% 
  add_p() %>%
  add_overall() %>% 
  add_n() 
```

-------------------------------------------------

#### 그룹간 차이
add_difference() 을 통해 그룹간 차이를 확인할 수 있다.

```{r, warning = FALSE, message = FALSE}
dt2 %>% select(-Q_SMK_YN, -EXMD_BZ_YYYY) %>% 
  tbl_summary(by = Q_PHX_DX_STK) %>%
  add_difference()
```

-------------------------------------------------

#### 테이블 디자인 및 포맷
* modify_header() : 테이블 header 형식 지정  
* modify_footnote() : 테이블 각주 형식 지정  
* modify_spanning_header() : 테이블 spanning header 형식 지정  
* modify_caption() : 테이블 캡션 형식 지정  
* bold_labels() : 변수명 볼드체  
* bold_levels() : 범주 볼드체  
* italicize_labels() : 변수명 기울임  
* italicize_levels() : 범주 기울임  
* bold_p() : p-value 볼드체

```{r}
MyTbl <- dt2 %>% 
  tbl_summary(by = EXMD_BZ_YYYY) %>%
  add_p() %>%
  add_n() %>% 
  modify_header(label ~ "**변수명**") %>% 
  modify_spanning_header(all_stat_cols() ~ "**해당연도**") %>% 
  modify_footnote(all_stat_cols() ~ "Median(IQR) 또는 Frequency(%)로 표기하였음") %>%
  modify_caption("연도별 기술통계량") %>% 
  bold_labels()
MyTbl
```

-------------------------------------------------

## 워드 파일로 저장하기
gtsummary 패키지를 이용해 만든 table을 flextable 객체로 바꾼 후 워드 파일로 저장할 수 있다.

```{r}
MyTbl %>% 
  as_flex_table() %>% 
  flextable::save_as_docx(MyTbl, path = "table1.docx")
```


출처: <https://blog.zarathu.com/>
